# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Sat Sep 19 20:47:55 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1546, 1292)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(1000000, 100000))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1522, 1175))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(50, 30, 441, 351))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 341, 111))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_chooseVisa = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa.setFont(font)
        self.label_chooseVisa.setObjectName(_fromUtf8("label_chooseVisa"))
        self.verticalLayout_4.addWidget(self.label_chooseVisa)
        self.comboBox_visa = QtGui.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_visa.setFont(font)
        self.comboBox_visa.setObjectName(_fromUtf8("comboBox_visa"))
        self.verticalLayout_4.addWidget(self.comboBox_visa)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_refresh = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_refresh.setFont(font)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.horizontalLayout_3.addWidget(self.pushButton_refresh)
        self.pushButton_select = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select.setFont(font)
        self.pushButton_select.setObjectName(_fromUtf8("pushButton_select"))
        self.horizontalLayout_3.addWidget(self.pushButton_select)
        self.pushButton_close = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 130, 341, 61))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_visa_address = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_address.setFont(font)
        self.label_visa_address.setText(_fromUtf8(""))
        self.label_visa_address.setObjectName(_fromUtf8("label_visa_address"))
        self.verticalLayout_2.addWidget(self.label_visa_address)
        self.layoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 190, 391, 61))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_visa_name = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_name.setFont(font)
        self.label_visa_name.setText(_fromUtf8(""))
        self.label_visa_name.setObjectName(_fromUtf8("label_visa_name"))
        self.verticalLayout_3.addWidget(self.label_visa_name)
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 250, 341, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_sweep_voltage = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_sweep_voltage.setFont(font)
        self.radioButton_sweep_voltage.setChecked(True)
        self.radioButton_sweep_voltage.setObjectName(_fromUtf8("radioButton_sweep_voltage"))
        self.horizontalLayout.addWidget(self.radioButton_sweep_voltage)
        self.radioButton_sweep_current = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_sweep_current.setFont(font)
        self.radioButton_sweep_current.setObjectName(_fromUtf8("radioButton_sweep_current"))
        self.horizontalLayout.addWidget(self.radioButton_sweep_current)
        self.layoutWidget_5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 290, 341, 41))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_2_point = QtGui.QRadioButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2_point.setFont(font)
        self.radioButton_2_point.setChecked(True)
        self.radioButton_2_point.setObjectName(_fromUtf8("radioButton_2_point"))
        self.horizontalLayout_2.addWidget(self.radioButton_2_point)
        self.radioButton_4_point = QtGui.QRadioButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4_point.setFont(font)
        self.radioButton_4_point.setObjectName(_fromUtf8("radioButton_4_point"))
        self.horizontalLayout_2.addWidget(self.radioButton_4_point)
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(510, 30, 391, 351))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_sweep_voltage = QtGui.QGroupBox(self.tab)
        self.groupBox_sweep_voltage.setGeometry(QtCore.QRect(0, 0, 401, 331))
        self.groupBox_sweep_voltage.setTitle(_fromUtf8(""))
        self.groupBox_sweep_voltage.setObjectName(_fromUtf8("groupBox_sweep_voltage"))
        self.label_13 = QtGui.QLabel(self.groupBox_sweep_voltage)
        self.label_13.setGeometry(QtCore.QRect(20, 280, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_voltage_time_measurements = QtGui.QLineEdit(self.groupBox_sweep_voltage)
        self.lineEdit_voltage_time_measurements.setGeometry(QtCore.QRect(270, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_voltage_time_measurements.setFont(font)
        self.lineEdit_voltage_time_measurements.setObjectName(_fromUtf8("lineEdit_voltage_time_measurements"))
        self.label_14 = QtGui.QLabel(self.groupBox_sweep_voltage)
        self.label_14.setGeometry(QtCore.QRect(350, 280, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.layoutWidget_7 = QtGui.QWidget(self.groupBox_sweep_voltage)
        self.layoutWidget_7.setGeometry(QtCore.QRect(50, 20, 281, 241))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_25 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_8.addWidget(self.label_25)
        self.lineEdit_start_voltage = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_start_voltage.setFont(font)
        self.lineEdit_start_voltage.setObjectName(_fromUtf8("lineEdit_start_voltage"))
        self.horizontalLayout_8.addWidget(self.lineEdit_start_voltage)
        self.label_26 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_8.addWidget(self.label_26)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_27 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_13.addWidget(self.label_27)
        self.lineEdit_top_voltage = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_top_voltage.setFont(font)
        self.lineEdit_top_voltage.setObjectName(_fromUtf8("lineEdit_top_voltage"))
        self.horizontalLayout_13.addWidget(self.lineEdit_top_voltage)
        self.label_28 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_13.addWidget(self.label_28)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_29 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_14.addWidget(self.label_29)
        self.lineEdit_end_voltage = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_end_voltage.setFont(font)
        self.lineEdit_end_voltage.setObjectName(_fromUtf8("lineEdit_end_voltage"))
        self.horizontalLayout_14.addWidget(self.lineEdit_end_voltage)
        self.label_30 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_14.addWidget(self.label_30)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_31 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_15.addWidget(self.label_31)
        self.lineEdit_time_steps_v = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_time_steps_v.setFont(font)
        self.lineEdit_time_steps_v.setObjectName(_fromUtf8("lineEdit_time_steps_v"))
        self.horizontalLayout_15.addWidget(self.lineEdit_time_steps_v)
        self.label_15 = QtGui.QLabel(self.layoutWidget_7)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.label_37 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_15.addWidget(self.label_37)
        self.label_32 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setText(_fromUtf8(""))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_15.addWidget(self.label_32)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_33 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_16.addWidget(self.label_33)
        self.lineEdit_current_limit = QtGui.QLineEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_current_limit.setFont(font)
        self.lineEdit_current_limit.setObjectName(_fromUtf8("lineEdit_current_limit"))
        self.horizontalLayout_16.addWidget(self.lineEdit_current_limit)
        self.label_34 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_16.addWidget(self.label_34)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_sweep_current = QtGui.QGroupBox(self.tab_2)
        self.groupBox_sweep_current.setGeometry(QtCore.QRect(0, 0, 401, 351))
        self.groupBox_sweep_current.setTitle(_fromUtf8(""))
        self.groupBox_sweep_current.setObjectName(_fromUtf8("groupBox_sweep_current"))
        self.label_23 = QtGui.QLabel(self.groupBox_sweep_current)
        self.label_23.setGeometry(QtCore.QRect(20, 280, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_current_time_measurements = QtGui.QLineEdit(self.groupBox_sweep_current)
        self.lineEdit_current_time_measurements.setGeometry(QtCore.QRect(270, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_current_time_measurements.setFont(font)
        self.lineEdit_current_time_measurements.setObjectName(_fromUtf8("lineEdit_current_time_measurements"))
        self.label_24 = QtGui.QLabel(self.groupBox_sweep_current)
        self.label_24.setGeometry(QtCore.QRect(350, 280, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.layoutWidget_6 = QtGui.QWidget(self.groupBox_sweep_current)
        self.layoutWidget_6.setGeometry(QtCore.QRect(50, 20, 281, 241))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_start_current = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_start_current.setFont(font)
        self.lineEdit_start_current.setObjectName(_fromUtf8("lineEdit_start_current"))
        self.horizontalLayout_4.addWidget(self.lineEdit_start_current)
        self.label_4 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_top_current = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_top_current.setFont(font)
        self.lineEdit_top_current.setObjectName(_fromUtf8("lineEdit_top_current"))
        self.horizontalLayout_5.addWidget(self.lineEdit_top_current)
        self.label_5 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_35 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_17.addWidget(self.label_35)
        self.lineEdit_end_current = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_end_current.setFont(font)
        self.lineEdit_end_current.setObjectName(_fromUtf8("lineEdit_end_current"))
        self.horizontalLayout_17.addWidget(self.lineEdit_end_current)
        self.label_36 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_17.addWidget(self.label_36)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_time_steps_c = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_time_steps_c.setFont(font)
        self.lineEdit_time_steps_c.setObjectName(_fromUtf8("lineEdit_time_steps_c"))
        self.horizontalLayout_6.addWidget(self.lineEdit_time_steps_c)
        self.label_16 = QtGui.QLabel(self.layoutWidget_6)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_6.addWidget(self.label_16)
        self.label_38 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setText(_fromUtf8(""))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.label_8 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lineEdit_voltage_limit = QtGui.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_voltage_limit.setFont(font)
        self.lineEdit_voltage_limit.setObjectName(_fromUtf8("lineEdit_voltage_limit"))
        self.horizontalLayout_7.addWidget(self.lineEdit_voltage_limit)
        self.label_10 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_7.addWidget(self.label_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_preview = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_preview.setGeometry(QtCore.QRect(920, 30, 561, 531))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_preview.setFont(font)
        self.groupBox_preview.setObjectName(_fromUtf8("groupBox_preview"))
        self.widget_time = QtGui.QWidget(self.groupBox_preview)
        self.widget_time.setGeometry(QtCore.QRect(10, 60, 541, 461))
        self.widget_time.setObjectName(_fromUtf8("widget_time"))
        self.mplwidget_time = MatplotlibWidget(self.widget_time)
        self.mplwidget_time.setGeometry(QtCore.QRect(260, 200, 16, 16))
        self.mplwidget_time.setObjectName(_fromUtf8("mplwidget_time"))
        self.label_17 = QtGui.QLabel(self.groupBox_preview)
        self.label_17.setGeometry(QtCore.QRect(30, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_preview = QtGui.QPushButton(self.groupBox_preview)
        self.pushButton_preview.setGeometry(QtCore.QRect(360, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_preview.setFont(font)
        self.pushButton_preview.setObjectName(_fromUtf8("pushButton_preview"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 891, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_halfbreak = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_halfbreak.setGeometry(QtCore.QRect(60, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_halfbreak.setFont(font)
        self.checkBox_halfbreak.setObjectName(_fromUtf8("checkBox_halfbreak"))
        self.groupBox_stop_continue = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_stop_continue.setEnabled(False)
        self.groupBox_stop_continue.setGeometry(QtCore.QRect(270, 20, 111, 91))
        self.groupBox_stop_continue.setTitle(_fromUtf8(""))
        self.groupBox_stop_continue.setObjectName(_fromUtf8("groupBox_stop_continue"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_stop_continue)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_Stop = QtGui.QPushButton(self.groupBox_stop_continue)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.verticalLayout.addWidget(self.pushButton_Stop)
        self.pushButton_Continue = QtGui.QPushButton(self.groupBox_stop_continue)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_Continue.setFont(font)
        self.pushButton_Continue.setObjectName(_fromUtf8("pushButton_Continue"))
        self.verticalLayout.addWidget(self.pushButton_Continue)
        self.groupBox_source = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_source.setEnabled(False)
        self.groupBox_source.setGeometry(QtCore.QRect(400, 20, 241, 91))
        self.groupBox_source.setTitle(_fromUtf8(""))
        self.groupBox_source.setObjectName(_fromUtf8("groupBox_source"))
        self.lineEdit_source = QtGui.QLineEdit(self.groupBox_source)
        self.lineEdit_source.setGeometry(QtCore.QRect(120, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_source.setFont(font)
        self.lineEdit_source.setObjectName(_fromUtf8("lineEdit_source"))
        self.label_18 = QtGui.QLabel(self.groupBox_source)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_source_unit = QtGui.QLabel(self.groupBox_source)
        self.label_source_unit.setGeometry(QtCore.QRect(210, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_source_unit.setFont(font)
        self.label_source_unit.setText(_fromUtf8(""))
        self.label_source_unit.setObjectName(_fromUtf8("label_source_unit"))
        self.label_19 = QtGui.QLabel(self.groupBox_source)
        self.label_19.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_measurement = QtGui.QLineEdit(self.groupBox_source)
        self.lineEdit_measurement.setGeometry(QtCore.QRect(120, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_measurement.setFont(font)
        self.lineEdit_measurement.setObjectName(_fromUtf8("lineEdit_measurement"))
        self.label_measurement_unit = QtGui.QLabel(self.groupBox_source)
        self.label_measurement_unit.setGeometry(QtCore.QRect(210, 50, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_measurement_unit.setFont(font)
        self.label_measurement_unit.setText(_fromUtf8(""))
        self.label_measurement_unit.setObjectName(_fromUtf8("label_measurement_unit"))
        self.pushButton_run = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_run.setGeometry(QtCore.QRect(710, 40, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_run.setFont(font)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(400, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_condition = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_condition.setGeometry(QtCore.QRect(490, 130, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_condition.setFont(font)
        self.lineEdit_condition.setObjectName(_fromUtf8("lineEdit_condition"))
        self.label_39 = QtGui.QLabel(self.groupBox_3)
        self.label_39.setGeometry(QtCore.QRect(30, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.lineEdit_run_name = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_run_name.setGeometry(QtCore.QRect(120, 130, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_run_name.setFont(font)
        self.lineEdit_run_name.setObjectName(_fromUtf8("lineEdit_run_name"))
        self.tabWidget_2 = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_2.setGeometry(QtCore.QRect(130, 570, 1231, 561))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(640, 10, 561, 501))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.widget_allplot = QtGui.QWidget(self.tab_6)
        self.widget_allplot.setGeometry(QtCore.QRect(10, 50, 541, 421))
        self.widget_allplot.setObjectName(_fromUtf8("widget_allplot"))
        self.mplwidget_allplot = MatplotlibWidget(self.widget_allplot)
        self.mplwidget_allplot.setGeometry(QtCore.QRect(170, 170, 151, 91))
        self.mplwidget_allplot.setObjectName(_fromUtf8("mplwidget_allplot"))
        self.tabWidget_3.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.widget_middle = QtGui.QWidget(self.tab_7)
        self.widget_middle.setGeometry(QtCore.QRect(10, 50, 541, 421))
        self.widget_middle.setObjectName(_fromUtf8("widget_middle"))
        self.mplwidget_middle = MatplotlibWidget(self.widget_middle)
        self.mplwidget_middle.setGeometry(QtCore.QRect(190, 120, 151, 91))
        self.mplwidget_middle.setObjectName(_fromUtf8("mplwidget_middle"))
        self.label_12 = QtGui.QLabel(self.tab_7)
        self.label_12.setGeometry(QtCore.QRect(60, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_best_fit_resistance = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_best_fit_resistance.setGeometry(QtCore.QRect(210, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_best_fit_resistance.setFont(font)
        self.lineEdit_best_fit_resistance.setText(_fromUtf8(""))
        self.lineEdit_best_fit_resistance.setObjectName(_fromUtf8("lineEdit_best_fit_resistance"))
        self.label_resistance_unit = QtGui.QLabel(self.tab_7)
        self.label_resistance_unit.setGeometry(QtCore.QRect(350, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resistance_unit.setFont(font)
        self.label_resistance_unit.setObjectName(_fromUtf8("label_resistance_unit"))
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.widget_right = QtGui.QWidget(self.tab_8)
        self.widget_right.setGeometry(QtCore.QRect(10, 50, 541, 421))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_right.sizePolicy().hasHeightForWidth())
        self.widget_right.setSizePolicy(sizePolicy)
        self.widget_right.setObjectName(_fromUtf8("widget_right"))
        self.mplwidget_right = MatplotlibWidget(self.widget_right)
        self.mplwidget_right.setGeometry(QtCore.QRect(200, 140, 151, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwidget_right.sizePolicy().hasHeightForWidth())
        self.mplwidget_right.setSizePolicy(sizePolicy)
        self.mplwidget_right.setObjectName(_fromUtf8("mplwidget_right"))
        self.label_20 = QtGui.QLabel(self.tab_8)
        self.label_20.setGeometry(QtCore.QRect(60, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_best_fit_resistance_descending = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_best_fit_resistance_descending.setGeometry(QtCore.QRect(210, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_best_fit_resistance_descending.setFont(font)
        self.lineEdit_best_fit_resistance_descending.setText(_fromUtf8(""))
        self.lineEdit_best_fit_resistance_descending.setObjectName(_fromUtf8("lineEdit_best_fit_resistance_descending"))
        self.label_resistance_unit_descending = QtGui.QLabel(self.tab_8)
        self.label_resistance_unit_descending.setGeometry(QtCore.QRect(350, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resistance_unit_descending.setFont(font)
        self.label_resistance_unit_descending.setObjectName(_fromUtf8("label_resistance_unit_descending"))
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 581, 511))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget_left = QtGui.QWidget(self.groupBox_2)
        self.widget_left.setGeometry(QtCore.QRect(20, 80, 541, 421))
        self.widget_left.setObjectName(_fromUtf8("widget_left"))
        self.mplwidget_left = MatplotlibWidget(self.widget_left)
        self.mplwidget_left.setGeometry(QtCore.QRect(190, 160, 151, 91))
        self.mplwidget_left.setObjectName(_fromUtf8("mplwidget_left"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_4)
        self.scrollArea_2.setGeometry(QtCore.QRect(40, 20, 1151, 471))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1149, 469))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.tableWidget_data = QtGui.QTableWidget(self.scrollAreaWidgetContents_2)
        self.tableWidget_data.setGeometry(QtCore.QRect(0, 0, 1151, 471))
        self.tableWidget_data.setObjectName(_fromUtf8("tableWidget_data"))
        self.tableWidget_data.setColumnCount(0)
        self.tableWidget_data.setRowCount(0)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_save = QtGui.QGroupBox(self.tab_5)
        self.groupBox_save.setEnabled(False)
        self.groupBox_save.setGeometry(QtCore.QRect(270, 30, 661, 431))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_save.setFont(font)
        self.groupBox_save.setObjectName(_fromUtf8("groupBox_save"))
        self.label_21 = QtGui.QLabel(self.groupBox_save)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_OneDrive = QtGui.QLineEdit(self.groupBox_save)
        self.lineEdit_OneDrive.setGeometry(QtCore.QRect(10, 90, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_OneDrive.setFont(font)
        self.lineEdit_OneDrive.setObjectName(_fromUtf8("lineEdit_OneDrive"))
        self.label_22 = QtGui.QLabel(self.groupBox_save)
        self.label_22.setGeometry(QtCore.QRect(10, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.comboBox_Name_Folder = QtGui.QComboBox(self.groupBox_save)
        self.comboBox_Name_Folder.setGeometry(QtCore.QRect(10, 210, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Name_Folder.setFont(font)
        self.comboBox_Name_Folder.setObjectName(_fromUtf8("comboBox_Name_Folder"))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.pushButton_Select_Directory = QtGui.QPushButton(self.groupBox_save)
        self.pushButton_Select_Directory.setGeometry(QtCore.QRect(200, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Select_Directory.setFont(font)
        self.pushButton_Select_Directory.setObjectName(_fromUtf8("pushButton_Select_Directory"))
        self.groupBox_File_Type = QtGui.QGroupBox(self.groupBox_save)
        self.groupBox_File_Type.setEnabled(False)
        self.groupBox_File_Type.setGeometry(QtCore.QRect(350, 40, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_File_Type.setFont(font)
        self.groupBox_File_Type.setObjectName(_fromUtf8("groupBox_File_Type"))
        self.radioButton_csv = QtGui.QRadioButton(self.groupBox_File_Type)
        self.radioButton_csv.setGeometry(QtCore.QRect(40, 20, 61, 31))
        self.radioButton_csv.setAcceptDrops(False)
        self.radioButton_csv.setAutoFillBackground(False)
        self.radioButton_csv.setChecked(True)
        self.radioButton_csv.setObjectName(_fromUtf8("radioButton_csv"))
        self.radioButton_txt = QtGui.QRadioButton(self.groupBox_File_Type)
        self.radioButton_txt.setGeometry(QtCore.QRect(160, 20, 61, 31))
        self.radioButton_txt.setObjectName(_fromUtf8("radioButton_txt"))
        self.groupBox_Filename = QtGui.QGroupBox(self.groupBox_save)
        self.groupBox_Filename.setEnabled(False)
        self.groupBox_Filename.setGeometry(QtCore.QRect(350, 110, 271, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_Filename.setFont(font)
        self.groupBox_Filename.setObjectName(_fromUtf8("groupBox_Filename"))
        self.radioButton_Timename = QtGui.QRadioButton(self.groupBox_Filename)
        self.radioButton_Timename.setGeometry(QtCore.QRect(20, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_Timename.setFont(font)
        self.radioButton_Timename.setChecked(True)
        self.radioButton_Timename.setObjectName(_fromUtf8("radioButton_Timename"))
        self.radioButton_Custom_Name = QtGui.QRadioButton(self.groupBox_Filename)
        self.radioButton_Custom_Name.setGeometry(QtCore.QRect(20, 70, 121, 21))
        self.radioButton_Custom_Name.setObjectName(_fromUtf8("radioButton_Custom_Name"))
        self.lineEdit_Custom_Name = QtGui.QLineEdit(self.groupBox_Filename)
        self.lineEdit_Custom_Name.setEnabled(False)
        self.lineEdit_Custom_Name.setGeometry(QtCore.QRect(40, 100, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Custom_Name.setFont(font)
        self.lineEdit_Custom_Name.setObjectName(_fromUtf8("lineEdit_Custom_Name"))
        self.pushButton_Save = QtGui.QPushButton(self.groupBox_save)
        self.pushButton_Save.setGeometry(QtCore.QRect(200, 320, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.pushButton_Open = QtGui.QPushButton(self.groupBox_save)
        self.pushButton_Open.setEnabled(False)
        self.pushButton_Open.setGeometry(QtCore.QRect(380, 320, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Open.setFont(font)
        self.pushButton_Open.setObjectName(_fromUtf8("pushButton_Open"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Visa Chosen", None))
        self.label_chooseVisa.setText(_translate("MainWindow", "Choose VISA", None))
        self.pushButton_refresh.setText(_translate("MainWindow", "Refresh", None))
        self.pushButton_select.setText(_translate("MainWindow", "Select", None))
        self.pushButton_close.setText(_translate("MainWindow", "Close", None))
        self.label.setText(_translate("MainWindow", "Current VISA address:", None))
        self.label_3.setText(_translate("MainWindow", "VISA name:", None))
        self.radioButton_sweep_voltage.setText(_translate("MainWindow", "Sweep Voltage", None))
        self.radioButton_sweep_current.setText(_translate("MainWindow", "Sweep Current", None))
        self.radioButton_2_point.setText(_translate("MainWindow", "2-Point Probe", None))
        self.radioButton_4_point.setText(_translate("MainWindow", "4-Point Probe", None))
        self.label_13.setText(_translate("MainWindow", "Time between two measurements:", None))
        self.lineEdit_voltage_time_measurements.setText(_translate("MainWindow", "0.001", None))
        self.label_14.setText(_translate("MainWindow", "s", None))
        self.label_25.setText(_translate("MainWindow", "Strat Voltage:  ", None))
        self.lineEdit_start_voltage.setText(_translate("MainWindow", "-200", None))
        self.label_26.setText(_translate("MainWindow", "  mV", None))
        self.label_27.setText(_translate("MainWindow", "Top Voltage:   ", None))
        self.lineEdit_top_voltage.setText(_translate("MainWindow", "200", None))
        self.label_28.setText(_translate("MainWindow", "  mV", None))
        self.label_29.setText(_translate("MainWindow", "End Voltage:   ", None))
        self.lineEdit_end_voltage.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "  mV", None))
        self.label_31.setText(_translate("MainWindow", "Steps Number:", None))
        self.lineEdit_time_steps_v.setText(_translate("MainWindow", "40", None))
        self.label_33.setText(_translate("MainWindow", "Current Limit: ", None))
        self.lineEdit_current_limit.setText(_translate("MainWindow", "100", None))
        self.label_34.setText(_translate("MainWindow", "  mA", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sweep Voltage", None))
        self.label_23.setText(_translate("MainWindow", "Time between two measurements:", None))
        self.lineEdit_current_time_measurements.setText(_translate("MainWindow", "0.001", None))
        self.label_24.setText(_translate("MainWindow", "s", None))
        self.label_2.setText(_translate("MainWindow", "Strat Current:  ", None))
        self.lineEdit_start_current.setText(_translate("MainWindow", "-10", None))
        self.label_4.setText(_translate("MainWindow", "  uA", None))
        self.label_6.setText(_translate("MainWindow", "Top Current:   ", None))
        self.lineEdit_top_current.setText(_translate("MainWindow", "10", None))
        self.label_5.setText(_translate("MainWindow", "  uA", None))
        self.label_35.setText(_translate("MainWindow", "End Current:   ", None))
        self.lineEdit_end_current.setText(_translate("MainWindow", "0", None))
        self.label_36.setText(_translate("MainWindow", "  uA", None))
        self.label_7.setText(_translate("MainWindow", "Steps Number:", None))
        self.lineEdit_time_steps_c.setText(_translate("MainWindow", "40", None))
        self.label_9.setText(_translate("MainWindow", "Voltage Limit: ", None))
        self.lineEdit_voltage_limit.setText(_translate("MainWindow", "400", None))
        self.label_10.setText(_translate("MainWindow", " mV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Current Sweep", None))
        self.groupBox_preview.setTitle(_translate("MainWindow", "Preview", None))
        self.label_17.setText(_translate("MainWindow", "Click to see Voltag (Current) vs.Real Time", None))
        self.pushButton_preview.setText(_translate("MainWindow", "Preview", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control ", None))
        self.checkBox_halfbreak.setText(_translate("MainWindow", "Stop During the Process", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop", None))
        self.pushButton_Continue.setText(_translate("MainWindow", "Continue", None))
        self.label_18.setText(_translate("MainWindow", "Source Value:", None))
        self.label_19.setText(_translate("MainWindow", "Measurement:", None))
        self.pushButton_run.setText(_translate("MainWindow", "RUN", None))
        self.label_11.setText(_translate("MainWindow", "Condition:", None))
        self.label_39.setText(_translate("MainWindow", "Run Name:", None))
        self.lineEdit_run_name.setText(_translate("MainWindow", "Resistance Measurement", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Full Points Plot", None))
        self.label_12.setText(_translate("MainWindow", "Best Fit Resistance:", None))
        self.label_resistance_unit.setText(_translate("MainWindow", "Ohms", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Ascedning Source Plot", None))
        self.label_20.setText(_translate("MainWindow", "Best Fit Resistance:", None))
        self.label_resistance_unit_descending.setText(_translate("MainWindow", "Ohms", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Descending Source Plot", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Real Time Plot", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Plotted Data", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Data Table", None))
        self.groupBox_save.setTitle(_translate("MainWindow", "Save", None))
        self.label_21.setText(_translate("MainWindow", "OneDrive directory:", None))
        self.lineEdit_OneDrive.setText(_translate("MainWindow", "C:\\Google Drive\\03 User Accounts", None))
        self.label_22.setText(_translate("MainWindow", "Pick up a name folder", None))
        self.comboBox_Name_Folder.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_Name_Folder.setItemText(1, _translate("MainWindow", "Horimbere", None))
        self.comboBox_Name_Folder.setItemText(2, _translate("MainWindow", "Sell", None))
        self.comboBox_Name_Folder.setItemText(3, _translate("MainWindow", "Snyder", None))
        self.comboBox_Name_Folder.setItemText(4, _translate("MainWindow", "Vannucci", None))
        self.comboBox_Name_Folder.setItemText(5, _translate("MainWindow", "Wang", None))
        self.comboBox_Name_Folder.setItemText(6, _translate("MainWindow", "Williams", None))
        self.pushButton_Select_Directory.setText(_translate("MainWindow", "Select", None))
        self.groupBox_File_Type.setTitle(_translate("MainWindow", "File type", None))
        self.radioButton_csv.setText(_translate("MainWindow", "csv", None))
        self.radioButton_txt.setText(_translate("MainWindow", "txt", None))
        self.groupBox_Filename.setTitle(_translate("MainWindow", "File name", None))
        self.radioButton_Timename.setText(_translate("MainWindow", "Date and time", None))
        self.radioButton_Custom_Name.setText(_translate("MainWindow", "Custom", None))
        self.pushButton_Save.setText(_translate("MainWindow", "Save", None))
        self.pushButton_Open.setText(_translate("MainWindow", "Open", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Save Data", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

