# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Sat Sep 19 20:33:47 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1268, 918)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1220, 830))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.pushButton_Refresh = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(320, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Refresh.setFont(font)
        self.pushButton_Refresh.setObjectName(_fromUtf8("pushButton_Refresh"))
        self.label_Current_Visa = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Current_Visa.setGeometry(QtCore.QRect(40, 620, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Current_Visa.setFont(font)
        self.label_Current_Visa.setObjectName(_fromUtf8("label_Current_Visa"))
        self.label_Meas_Type = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Meas_Type.setGeometry(QtCore.QRect(40, 680, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Meas_Type.setFont(font)
        self.label_Meas_Type.setObjectName(_fromUtf8("label_Meas_Type"))
        self.pushButton_Select_Visa = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Select_Visa.setGeometry(QtCore.QRect(320, 600, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Select_Visa.setFont(font)
        self.pushButton_Select_Visa.setObjectName(_fromUtf8("pushButton_Select_Visa"))
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(370, 700, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_Steps = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Steps.setGeometry(QtCore.QRect(730, 650, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Steps.setFont(font)
        self.lineEdit_Steps.setObjectName(_fromUtf8("lineEdit_Steps"))
        self.groupBox_Filename = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_Filename.setGeometry(QtCore.QRect(840, 730, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_Filename.setFont(font)
        self.groupBox_Filename.setObjectName(_fromUtf8("groupBox_Filename"))
        self.radioButton_Timename = QtGui.QRadioButton(self.groupBox_Filename)
        self.radioButton_Timename.setGeometry(QtCore.QRect(20, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radioButton_Timename.setFont(font)
        self.radioButton_Timename.setObjectName(_fromUtf8("radioButton_Timename"))
        self.radioButton_Custom_Name = QtGui.QRadioButton(self.groupBox_Filename)
        self.radioButton_Custom_Name.setGeometry(QtCore.QRect(20, 50, 121, 21))
        self.radioButton_Custom_Name.setObjectName(_fromUtf8("radioButton_Custom_Name"))
        self.lineEdit_Custom_Name = QtGui.QLineEdit(self.groupBox_Filename)
        self.lineEdit_Custom_Name.setGeometry(QtCore.QRect(120, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Custom_Name.setFont(font)
        self.lineEdit_Custom_Name.setObjectName(_fromUtf8("lineEdit_Custom_Name"))
        self.lineEdit_Points = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Points.setGeometry(QtCore.QRect(730, 560, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Points.setFont(font)
        self.lineEdit_Points.setObjectName(_fromUtf8("lineEdit_Points"))
        self.lineEdit_Error = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Error.setGeometry(QtCore.QRect(450, 710, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_Error.setFont(font)
        self.lineEdit_Error.setObjectName(_fromUtf8("lineEdit_Error"))
        self.pushButton_Start = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Start.setGeometry(QtCore.QRect(510, 780, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.comboBox_All_Visas = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_All_Visas.setGeometry(QtCore.QRect(40, 580, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_All_Visas.setFont(font)
        self.comboBox_All_Visas.setObjectName(_fromUtf8("comboBox_All_Visas"))
        self.pushButton_Select_Directory = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Select_Directory.setGeometry(QtCore.QRect(1070, 690, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Select_Directory.setFont(font)
        self.pushButton_Select_Directory.setObjectName(_fromUtf8("pushButton_Select_Directory"))
        self.pushButton_Select_Measurement = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Select_Measurement.setGeometry(QtCore.QRect(250, 710, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Select_Measurement.setFont(font)
        self.pushButton_Select_Measurement.setObjectName(_fromUtf8("pushButton_Select_Measurement"))
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(850, 670, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.checkBox_Continue = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_Continue.setGeometry(QtCore.QRect(480, 580, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_Continue.setFont(font)
        self.checkBox_Continue.setObjectName(_fromUtf8("checkBox_Continue"))
        self.pushButton_Browse = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Browse.setGeometry(QtCore.QRect(850, 560, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Browse.setFont(font)
        self.pushButton_Browse.setObjectName(_fromUtf8("pushButton_Browse"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(40, 550, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_Meas_Type = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Meas_Type.setGeometry(QtCore.QRect(40, 710, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Meas_Type.setFont(font)
        self.comboBox_Meas_Type.setObjectName(_fromUtf8("comboBox_Meas_Type"))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.comboBox_Meas_Type.addItem(_fromUtf8(""))
        self.groupBox_File_Type = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_File_Type.setGeometry(QtCore.QRect(970, 550, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_File_Type.setFont(font)
        self.groupBox_File_Type.setObjectName(_fromUtf8("groupBox_File_Type"))
        self.radioButton_csv = QtGui.QRadioButton(self.groupBox_File_Type)
        self.radioButton_csv.setGeometry(QtCore.QRect(40, 20, 61, 31))
        self.radioButton_csv.setObjectName(_fromUtf8("radioButton_csv"))
        self.radioButton_txt = QtGui.QRadioButton(self.groupBox_File_Type)
        self.radioButton_txt.setGeometry(QtCore.QRect(100, 20, 61, 31))
        self.radioButton_txt.setObjectName(_fromUtf8("radioButton_txt"))
        self.label_CurrentMeasurement = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_CurrentMeasurement.setGeometry(QtCore.QRect(40, 770, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_CurrentMeasurement.setFont(font)
        self.label_CurrentMeasurement.setText(_fromUtf8(""))
        self.label_CurrentMeasurement.setObjectName(_fromUtf8("label_CurrentMeasurement"))
        self.pushButton_Save = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Save.setGeometry(QtCore.QRect(1120, 750, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.lineEdit_OneDrive = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_OneDrive.setGeometry(QtCore.QRect(850, 630, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_OneDrive.setFont(font)
        self.lineEdit_OneDrive.setObjectName(_fromUtf8("lineEdit_OneDrive"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(850, 600, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_CurrentVisa = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_CurrentVisa.setGeometry(QtCore.QRect(40, 640, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_CurrentVisa.setFont(font)
        self.label_CurrentVisa.setText(_fromUtf8(""))
        self.label_CurrentVisa.setObjectName(_fromUtf8("label_CurrentVisa"))
        self.comboBox_Name_Folder = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Name_Folder.setGeometry(QtCore.QRect(850, 690, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_Name_Folder.setFont(font)
        self.comboBox_Name_Folder.setObjectName(_fromUtf8("comboBox_Name_Folder"))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.comboBox_Name_Folder.addItem(_fromUtf8(""))
        self.label_Meas_Points = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Meas_Points.setGeometry(QtCore.QRect(450, 560, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Meas_Points.setFont(font)
        self.label_Meas_Points.setObjectName(_fromUtf8("label_Meas_Points"))
        self.label_second = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_second.setGeometry(QtCore.QRect(810, 660, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_second.setFont(font)
        self.label_second.setObjectName(_fromUtf8("label_second"))
        self.pushButton_Stop = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Stop.setGeometry(QtCore.QRect(630, 780, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.label_Meas_Delay = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Meas_Delay.setGeometry(QtCore.QRect(450, 650, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_Meas_Delay.setFont(font)
        self.label_Meas_Delay.setObjectName(_fromUtf8("label_Meas_Delay"))
        self.curvewidgetPlot = CurveWidget(self.scrollAreaWidgetContents)
        self.curvewidgetPlot.setGeometry(QtCore.QRect(210, 40, 771, 471))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.curvewidgetPlot.setFont(font)
        self.curvewidgetPlot.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidgetPlot.setObjectName(_fromUtf8("curvewidgetPlot"))
        self.label_Step_Reminder = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Step_Reminder.setGeometry(QtCore.QRect(470, 670, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Step_Reminder.setFont(font)
        self.label_Step_Reminder.setText(_fromUtf8(""))
        self.label_Step_Reminder.setObjectName(_fromUtf8("label_Step_Reminder"))
        self.label_Current_Measurement = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Current_Measurement.setGeometry(QtCore.QRect(40, 750, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Current_Measurement.setFont(font)
        self.label_Current_Measurement.setObjectName(_fromUtf8("label_Current_Measurement"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh", None))
        self.label_Current_Visa.setText(_translate("MainWindow", "Current visa address:", None))
        self.label_Meas_Type.setText(_translate("MainWindow", "Choose one you want to measure", None))
        self.pushButton_Select_Visa.setText(_translate("MainWindow", "Select", None))
        self.label_2.setText(_translate("MainWindow", "Condition:", None))
        self.groupBox_Filename.setTitle(_translate("MainWindow", "File name", None))
        self.radioButton_Timename.setText(_translate("MainWindow", "Date and time", None))
        self.radioButton_Custom_Name.setText(_translate("MainWindow", "Custom", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Select_Directory.setText(_translate("MainWindow", "Select", None))
        self.pushButton_Select_Measurement.setText(_translate("MainWindow", "Select", None))
        self.label_4.setText(_translate("MainWindow", "Pick up a name folder", None))
        self.checkBox_Continue.setText(_translate("MainWindow", "Continue Measure Mode", None))
        self.pushButton_Browse.setText(_translate("MainWindow", "Browse", None))
        self.label.setText(_translate("MainWindow", "Choose the visa you need", None))
        self.comboBox_Meas_Type.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_Meas_Type.setItemText(1, _translate("MainWindow", "AC Current", None))
        self.comboBox_Meas_Type.setItemText(2, _translate("MainWindow", "DC Current", None))
        self.comboBox_Meas_Type.setItemText(3, _translate("MainWindow", "AC Voltage", None))
        self.comboBox_Meas_Type.setItemText(4, _translate("MainWindow", "DC Voltage", None))
        self.comboBox_Meas_Type.setItemText(5, _translate("MainWindow", "Resistance", None))
        self.groupBox_File_Type.setTitle(_translate("MainWindow", "File type", None))
        self.radioButton_csv.setText(_translate("MainWindow", "csv", None))
        self.radioButton_txt.setText(_translate("MainWindow", "txt", None))
        self.pushButton_Save.setText(_translate("MainWindow", "Save", None))
        self.lineEdit_OneDrive.setText(_translate("MainWindow", "C:\\Google Drive\\03 User Accounts", None))
        self.label_3.setText(_translate("MainWindow", "OneDrive directory:", None))
        self.comboBox_Name_Folder.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_Name_Folder.setItemText(1, _translate("MainWindow", "Snyder", None))
        self.comboBox_Name_Folder.setItemText(2, _translate("MainWindow", "Wang", None))
        self.comboBox_Name_Folder.setItemText(3, _translate("MainWindow", "Williams", None))
        self.comboBox_Name_Folder.setItemText(4, _translate("MainWindow", "Vannucci", None))
        self.label_Meas_Points.setText(_translate("MainWindow", "How many points you want to plot?", None))
        self.label_second.setText(_translate("MainWindow", "s", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop", None))
        self.label_Meas_Delay.setText(_translate("MainWindow", "How long do you want for time step?", None))
        self.label_Current_Measurement.setText(_translate("MainWindow", "Current measurement:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Continuous Readings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Hardware Triggering", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Visa Controls", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

from guiqwt.plot import CurveWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

